
# Use root/example as user/password credentials
version: '2'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    hostname: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: emails
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
  php:
    image: skick6/phpserver
    restart: always
    depends_on:
      - db
    ports:
      - 8082:80
    volumes:
      - ./src/:/var/www/html/
